scrape_configs:
  - job_name: node
    scrape_interval: 15s
    static_configs:
      - targets: ["172.18.68.58:9100"] # altere para o ip da sua maquina

  - job_name: "otel-collector"
    scrape_interval: 1s
    static_configs:
      - targets: ["otel-collector:8889"]
      - targets: ["otel-collector:8888"]
